POST http://localhost:3333/events
Content-Type: application/json

{
	"title": "Novo evento",
	"details": null,
	"maximumAttendees": 1
}

###

POST http://localhost:3333/events/1de624aa-e4ab-44e4-adef-539cf3f42857/attendees
Content-Type: application/json

{
	"name": "Daiana de Paula",
	"email": "daiana1@gmail.com"
}